version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - L5_SWAGGER_GENERATE_ALWAYS=false
    depends_on:
      - db
    volumes:
      - ./storage:/var/www/html/storage

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
